### ISSUE TITLE
Passing Tempfile from Rack to Exif::Data.new raises an error

### ISSUE THREAD

**Issue by Aupajo** [tonytonyjan/exif#13]
If I have an upload coming from Rack:

```
> file
#<Tempfile:/var/folders/r4/rd0m9j997h19dm1nz9_fg2540000gn/T/RackMultipart20171019-54278-1v4nvvt.jpg>
```

If I try to parse it with `Exif::Data.new`, I get the following error:

```
> Exif::Data.new(file)
TypeError: wrong argument type Tempfile (expected String or IO)
```

**Comment by tonytonyjan** [comment]
This is expected behavior since `Tempfile` is not an `IO` but a `DelegateClass(File)`. A workaround would be calling `Tempfile#read` before passing it to `Exif::Data.new`.

In fact, I am thinking about to add a feature to support objects with some interfaces like `#read` being implemented and thus some built-in class like `StringIO` and `Tempfile` can work.

**Comment by Aupajo** [comment]
@tonytonyjan That sounds ideal – if the object responds to `read`

**Comment by tonytonyjan** [comment]
exif v2.1.0 has been released and it should solve this issue. Thanks for making exif better :)

**Comment by Aupajo** [comment]
@tonytonyjan Thank you for the quick fix 😄
