### ISSUE TITLE
Interpreting GPS coordinates

### ISSUE THREAD

**Issue by chadwilken** [tonytonyjan/exif#21]
I updated to 2.2.0 from 1.0.1 and the GPS coordinates are presented at:
```
@gps_latitude=[(40/1), (48/1), (541/10)]
@gps_latitude_ref="N"
@gps_longitude=[(96/1), (42/1), (1679/50)]
@gps_longitude_ref="W"
```
in 2.2.0. How am I supposed to interpret these values? Sorry if this is a dumb question.

**Comment by tonytonyjan** [comment]
please see the [CHANGELOG](https://github.com/tonytonyjan/exif/blob/master/CHANGELOG.md#breaking-changes):

> Instead of returning String, all tags are now typecasted according to TIFF tag. Tags for time like DateTimeOriginal is nolonger typecasted to Time object

Since 2.0, GPS coordinates data will now return an array of rational numbers instead of a float type, for example:

<img width="745" alt="screen shot 2018-10-25 at 8 44 04 am" src="https://user-images.githubusercontent.com/809410/47469191-2aa1a080-d832-11e8-8509-883190a91105.png">

To convert it to float, you can try this:

```ruby
def geo_float(degrees, minutes, seconds)
  degrees + minutes / 60.0 + seconds / 3600.0
end
@gps_latitude = [Rational(40 / 1), Rational(48 / 1), Rational(541 / 10)]
geo_float(*gps_latitude) # => 40.815
```

**Comment by chadwilken** [comment]
Perfect, thank for the in-depth answer!
-- 
*Chad Wilken*
1125 Aberdeen Avenue
Lincoln, NE 68512
(402) 405-7300

**Comment by tonytonyjan** [comment]
# 🍻
