### ISSUE TITLE
HEIC Support?

### ISSUE THREAD

**Issue by chadwilken** [tonytonyjan/exif#22]
I'm trying to read HEIC files from Apple devices but the lib returns a `NullExif`. I assume this probably is at the fault of `libexif` rather then this gem but want to see if you have a work-around or know of a way to fix this?

**Comment by tonytonyjan** [comment]
Hi @chadwilken, thanks for trying this gem, unfortunately, I am not familiar with handling HEIC files. The main problem would be libexif does not support file formats like HEIC.

One workaround I could figure out is that converting HEIC files into JPEG by 3rd tools such as ImageMagick before retrieving EXIF by the gem.

Alternatively, if you don't mind using other tools rather than this gem, ExifTool could be a good option.

**Comment by chadwilken** [comment]
I just noticed that it worked after conversion. I think I will go that route for now. Thanks!

**Comment by tonytonyjan** [comment]
My pleasure =D
I would close this issue, if you have any question, feel free to create another issue.
